---
title: "Filematrix vs. bigmemory (packages)"
author: "Andrey Shabalin, blah blah blah"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Filematrix vs. bigmemory (packages)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Motivation for creation of `filematrix` package

The `filematrix` package was originally conceived as an alternative to `bigmemory` package for two reasons.
First, `bigmemory` was **not available for Windows** for over a year. It is fully cross platform now, but it was not always the case.
Second, matrices created with `bigmemory` on NFS (network file system) have often been **corrupted** (contained all zeros). This was most likely a fault of memory-mapped files on NFS. 

### Differences between `filematrix` and `bigmemory` packages

The packages use different libraries to read from and write to their big files. 
Filematrix uses `readBin` and `writeBin` R functions. Bigmemory uses memory-mapped file access via `BH` R package (Boost C++).

Also, filematrix can store real values in `short` 4 byte format, `bigmemory` does not support it.

### Differences in tests

Due to different file access approach:

- `bigmemory` accumulates changes to the matrix in memory and writes them to the file upon call of `flush` or file closure.
- `filematrix` writes the changes to the file upon the request without delay.

Consequently:

- `bigmemory` works well for matrices smaller than the system memory. Writing to larger matrices is much slower due to system trying to keep as much of the matrix in the system memory (cache) as possible.
- `filematrix`'s performance does not deteriorate on matrices many times larger than the system memory.

- `bigmemory` is better for more random access of the file matrices.
- `filematrix` is equally good or better for block and column-wise access of the file matrices.


